using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Assembly.IO;

namespace HscTool.Blam
{
    public class HscFile
    {
        public HscFile(IReader reader)
        {
            Read(reader);
        }
        string _name;
        Int32 _size;
        UInt32 _address;
        HscType _type;

        public string Name { get { return _name; } }
        public Int32 Size { get { return _size; } }
        public UInt32 Address { get { return _address; } }
        public HscType Type { get { return _type; } }

        public void Read(IReader reader)
        {
            _name = reader.ReadAscii(32);
            _size = reader.ReadInt32();
            reader.Skip(8);
            _address = reader.ReadUInt32();
            reader.Skip(4);
            _type = (HscType)reader.ReadInt32();
        }
    }

    public enum HscType
    {
        ScriptFile = 0x0,
        AutoGeneratedCinematicScript = 0x1,
        AiObjectiveFragments = 0x3,
        AiPerformanceFragments = 0x5
    }
}
